### PR TITLE
Add attacks to states

### LINKED ISSUE #19: Add support for dash inertia when coming from a dash to a jump
The idea if that when doing this further dashes are unavailable, but the jump will maintain its horizontal velocity. Just like in Megaman X when you jump in the middle of a dash, aka dash jumps.

### LINKED ISSUE #37: Port Platform related classes to Physics Prototype

### LINKED ISSUE #48: Add Attacks to States

### PR DESCRIPTION
**Pull request by henriiquecampos**
Close #48 Close #19 and Close #37

I am not sure if I should have a dedicated State for each `*State/Attack`, e.g. an IdleAttackState for when the `Idle/Attack` executes.

As is currently each State mutates the `Attacks.current`, setting it to be the respective set of `Attacks` and `Combos` that are performed in this `State`. So e.g.:

1. IdleState enters
2. IdleState sets Attacks.current to `IdleAttacks`
3. IdleState/Attack executes
4. Attacks.current executes

The Attacks can't be a child of any State, as Attack has transform properties, e.g. position.

So I'm thinking if I should either:
1. Create a new `*AttackState` for each State that can execute an `Attack`
2. Keep as is, with `*State/Attack` doing no transitions.

### CODE REVIEW

**Comment by razcore-rad** [comment]
So I quickly looked at the game, it wasn't easy to figure out what to do, I know from the inside it's obvious for you but I never looked at the game before, I at least expected it to have a default/main scene that it would run when pressing `F5`

On the state machine topic, I see you already took an interesting approach with using the command pattern to compose states. But I guess you found the limit of the *regular* FSM implementation which is: you often run into duplication of code and exponential state growth.

Although, having many states with duplicated code is acceptable, you'll probably run into trouble trying to keep everything in sync. While the other problem is the combination of all possible states could get out of hand.

I'm not sure how this would work with something like we implemented in the Metroidvania2D course game where we use a HFSM, that said I don't see why it wouldn't work with composing states with the help of the command pattern. The main takeaway from our HFSM is that only leaf nodes (states) are active, parent nodes (states) encapsulate the common code among all leaf states.

It isn't easy to conceptualize or to manage HFSM's either since it's not necessarily a natural hierarchy. In your case for example, I would probably have a `Dash` state as a leaf state instead of a parent state and it would most likely be a child of a `Move` state of sorts. I don't think there's an easy way to tackle this in your implementation since it's just a limit that *regular* FSMs run into.

On the topic of attacks, again, in Metroidvania2D the solution is to have concurrent FSMs. We have a state machine for the player and an independent state machine for the hook tool/weapon. This is also a pretty common pattern, you don't have to cram up everything in one single state machine. It's also very well covered in http://gameprogrammingpatterns.com/state.html#concurrent-state-machines so I encourage you to go read that chapter.

**Comment by NathanLovato** [comment]
FSMs are common in controllers - menu transitions, playable character, simple ai... as long as you have a finite number of behaviors your object can be in. The playable character in a polished single-player game tends to get so specific the states aren't too reusable, so it's not always worth making it too flexible or breaking the code down a lot. It's a balancing act, between the time it takes to break down and refactor the code and the measure of how much you'll reuse it. There's no silver bullet.

I don't know of many alternatives for the type of game you're creating, in an engine that favors OO like Godot.

In larger games with complex AI, the playable characters can rely on a behavior tree. Your convert the player input into information the tree can process, making playable characters and AI work the same way. 

With an FSM you can do that, or the opposite: convert the AI's decisions into input events, to reuse states between player and AI characters. It can be tricky to design an AI that's "pressing keys" at first as it's not intuitive to think of it as a player, but I've heard it's used in e.g. fighting games.

**Comment by henriiquecampos** [comment]
Thanks for your insights!

I didn't remember the concurrent State Machines part of this book, thanks a lot @razcore-art it seems to be a good alternative for what I'm facing here, the approach was close enough so that I could just change the `Attacks`' script to be a FSM. I will test a bit more this week, but seems like this will be the approach I will take, so the attack input events are sent to the `CombatStateMachine` instead of to the StateMachine responsible for the movement, which indeed makes no sense.

@NathanLovato I'm trying to throw this *specificity* on the `.tscn` instead of the script themselves, so that the data is *ad hoc* but the logic isn't. E.g. the `States`' transitions are made with signals using the Editor's interface, so that the signal connections and extra args are stored in the `.tscn` file itself. Hopefully, this will help make this reusable, but I will still have to test how it behaves with other games, e.g. I can think of using it with a Top Down already :thinking:

**Comment by NathanLovato** [comment]
> Hopefully, this will help make this reusable, but I will still have to test how it behaves with other games, e.g. I can think of using it with a Top Down already thinking

In my experience, it's hard to reuse gameplay code in different games past basic foundations if you want to produce polished results. That is because when you start to add animations, refine the game's feel, the code's complexity and connections in the code grow quite a bit. For the course, we've spent quite a lot of time cleaning up the code, but in production, working on a game, I'd only refactor the parts that need refactoring, when they need refactoring.

The patterns and utilities are always reusable, no problem there. You can have reusable gameplay systems too, game-specific frameworks, but I think they take careful planning and tend to get surprisingly time-consuming. 

When we were working together with Florian, we'd reuse UI and boilerplate code across projects. He'd code the gameplay from scratch every time, and we'd ship and sell games fast. We had the complete gameplay prototype with art within 1 to 2 days every time. The games weren't great as we had little experience with design and tight tech constraints. But we were productive. And we were building up and improving our boilerplate code as we sold new titles to publishers. Sometimes I wish we had a way to do that with GDQuest's projects as well.

It's good to experiment anyway. Keep it up. I'm just sharing personal experience.

**Comment by henriiquecampos** [comment]
Yep! At some point we all need ad hoc solutions, otherwise, we only have very generic games, right? :laughing: 

Anyway, I'd like to thank all the insights you all gave me, I decided to go with this concurrent FSM approach!

**Pull request merged**
